sudo: false
language: ruby
rvm:
  - 2.0.0
before_install:
  - gem install bundler
script:
  - bundle exec rake test:units FOG_MOCK=true COVERAGE=true
  - bundle exec rake test:integration FOG_MOCK=true
  - bundle exec rake rubocop
